/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-10-13 15:54:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class warmService_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 String basePath=request.getScheme() + "://" +
request.getServerName() + ":" + request.getServerPort() +
request.getContextPath() + "/"; 
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>温馨服务t</title>\n");
      out.write("\t\t<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("\t\t<!-- Custom Theme files -->\n");
      out.write("\t\t<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("\t\t<!-- Custom Theme files -->\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<!-- Custom Theme files -->\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t\t<meta name=\"keywords\" content=\"My Show Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, \n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style_footer.css\" />\n");
      out.write("\t\t<script type=\"application/x-javascript\">\n");
      out.write("\t\t\taddEventListener(\"load\", function() {\n");
      out.write("\t\t\t\tsetTimeout(hideURLbar, 0);\n");
      out.write("\t\t\t}, false);\n");
      out.write("\n");
      out.write("\t\t\tfunction hideURLbar() {\n");
      out.write("\t\t\t\twindow.scrollTo(0, 1);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<!--webfont-->\n");
      out.write("\t\t<link href='#css?family=Oxygen:400,700,300' rel='stylesheet' type='text/css'>\n");
      out.write("\t\t<link href='#css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("\t\t<!-- start menu -->\n");
      out.write("\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style_nav.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/news-nav.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("\n");
      out.write("\t\t<link href=\"css/megamenu.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/megamenu.js\"></script>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t$(\".megamenu\").megamenu();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery.leanModal.min.js\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/menu.css\" />\n");
      out.write("\t\t<script src=\"js/easyResponsiveTabs.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t$('#horizontalTab').easyResponsiveTabs({\n");
      out.write("\t\t\t\t\ttype: 'default', //Types: default, vertical, accordion           \n");
      out.write("\t\t\t\t\twidth: 'auto', //auto or any width like 600px\n");
      out.write("\t\t\t\t\tfit: true // 100% fit in a container\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t\t<!---- start-smoth-scrolling---->\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/easing.js\"></script>\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tjQuery(document).ready(function($) {\n");
      out.write("\t\t\t\t$(\".scroll\").click(function(event) {\n");
      out.write("\t\t\t\t\tevent.preventDefault();\n");
      out.write("\t\t\t\t\t$('html,body').animate({\n");
      out.write("\t\t\t\t\t\tscrollTop: $(this.hash).offset().top\n");
      out.write("\t\t\t\t\t}, 1200);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<!---- start-smoth-scrolling---->\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\t<!-- header-section-starts -->\n");
      out.write("\t\t<div class=\"tm-header\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-4 col-sm-3 tm-site-name-container\">\n");
      out.write("\t\t\t\t\t\t<a href=\"NotIndex.html\" class=\"tm-site-name\"><img src=\"images/logo2.jpg\" style=\"position: relative;top: -15px;\"></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-8 col-sm-9\">\n");
      out.write("\t\t\t\t\t\t<div class=\"mobile-menu-icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<nav class=\"tm-nav\" style=\"width: 600px;\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"../main/NotIndex\" >主页</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"../userweb/NormalQuestion\">常见问题</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"../purchase/CommonSence\">铁路常识</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"../purchase/zcfc\">站车风采</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"../purchase/warmService\">温馨服务</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--//logo-->\n");
      out.write("\t\t\t<div class=\"w3layouts-login\">\n");
      out.write("\t\t\t\t\t<a  href=\"../userweb/first\"><i class=\"glyphicon glyphicon-user\"> </i>个人中心</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"faq\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"agileits-news-top\">\n");
      out.write("\t\t\t\t\t<ol class=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"../main/NotIndex\" >主页</a></li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li class=\"active\">温馨服务</li>\n");
      out.write("\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\" style=\"margin-bottom: 100px;\">\n");
      out.write("\t\t\t<div class=\"main-content\">\n");
      out.write("\t\t\t\t<div class=\"e-payment-section\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-* payment-left\">\n");
      out.write("\t\t\t\t\t\t<div class=\"payment-options\">\n");
      out.write("\t\t\t\t\t\t\t<h3>温馨服务：</h3>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tabs-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"tabs-menu booking-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"btn-primary\" style=\"text-align: center;font-size: 16px;\" href=\"#tab1\">全部服务列表</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"btn-primary\" style=\"margin-top: 2px;text-align: center;font-size: 16px\" href=\"#tab2\">遗失物品查找</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"btn-primary\" style=\"margin-top: 2px;text-align: center;font-size: 16px\" href=\"#tab3\">重点旅客预约</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab-grids event-tab-grids\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tab1\" class=\"tab-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><img src=\"images/ServiceList.PNG\" width=\"950\"></p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tab2\" class=\"tab-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"table-responsive\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<caption><h1>失物列表</h1></caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>遗失物品</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>物品描述</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>拾到时间</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>拾到地点</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>领取地点</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>领取状态</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>已领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>已领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>01/08/2017</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"success\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>耳机</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>苹果，银色</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/07/2017</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>已领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>充电宝</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>小米，银色，底部有明显划痕</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>23/11/2013</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>火车站检票进站处</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>售票厅服务台</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>未领取</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"position: relative;left: 350px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&laquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">1</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">2</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">3</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">4</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">5</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&raquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tab3\" class=\"tab-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 style=\"text-align: center;\">重点旅客预约流程</h1><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em></em><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>1.首先，用户进入到snail官方网站，点击新版售票选项。进入到新版售票的界面。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>2.进入到新版售票界面后，用户点击界面右上角箭头所指处的【登录】选项。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>3.在登录界面上，用户输入自己的用户登录名、登录密码和验证码，完成登录操作。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>4.完成登录操作后，用户进入到【个人中心】选项，之后点击左侧的【重点旅客预约】选项。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>5.用户在使用重点旅客预约】服务的时候，需要认真阅读重点旅客预约可以享受哪些权利和义务，之后点击同意。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>6.点击同意后，用户就可以填写一张重点旅客预约服务单了，提交审核通过后，重点旅客就可以享受提前进、离站，</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\t携带导盲犬等特殊服务了。</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em></em><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em></em><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em></em><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>发布时间：2017.08.01</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>发布单位：Snail官方网站</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--start-carrer-->\n");
      out.write("\t\t\t\t\t\t\t<!----- Comman-js-files ----->\n");
      out.write("\t\t\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#tab2\").hide();\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#tab3\").hide();\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#tab4\").hide();\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".tabs-menu a\").click(function(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\tevent.preventDefault();\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tab = $(this).attr(\"href\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".tab-grid\").not(tab).css(\"display\", \"none\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(tab).fadeIn(\"slow\");\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t</script>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"cuttingLine1\">\n");
      out.write("\t\t\t<div class=\"tm-section-header\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-3\">\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t<h1 class=\"tm-section-title\" style=\"font-family:'century gothic';\">ABOUT US</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-3\">\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<footer id=\"footerContainer\">\n");
      out.write("\t\t\t<div class=\"footer\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"quicklinks\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"footerh\"><font><font>相关链接</font></font></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-angle-right\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<font>企业差旅索引</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-angle-right\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<font>网络社会征信网</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-angle-right\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<font>加盟合作</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"quickcontact\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"footerh\"><font><font>联系我们</font></font></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font> 123456789</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-envelope\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font> abc@website.com</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font> 2B Barcelon，纽约-32011</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-sm-12 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"follow\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"footerh\"><font><font>微信公众号</font></font></h4>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/er_ctrip_wechat.jpg\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"background: white;\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t<p style=\"color: black;\">\n");
      out.write("\t\t\t\t\t\t\t<font>\n");
      out.write("\t\t\t\t\t\t\t\t<font>版权所有©2017.公司名称保留所有权利。\n");
      out.write("\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"toTopButton\"></div>\n");
      out.write("\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t<script src=\"js/responsive-tabs.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$('#myTab a').click(function(e) {\n");
      out.write("\t\t\t\te.preventDefault();\n");
      out.write("\t\t\t\t$(this).tab('show');\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t$('#moreTabs a').click(function(e) {\n");
      out.write("\t\t\t\te.preventDefault();\n");
      out.write("\t\t\t\t$(this).tab('show');\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t(function($) {\n");
      out.write("\t\t\t\t// Test for making sure event are maintained\n");
      out.write("\t\t\t\t$('.js-alert-test').click(function() {\n");
      out.write("\t\t\t\t\talert('Button Clicked: Event was maintained');\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\tfakewaffle.responsiveTabs(['xs', 'sm']);\n");
      out.write("\t\t\t})(jQuery);\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t$().UItoTop({\n");
      out.write("\t\t\t\t\teasingType: 'easeOutQuart'\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<a href=\"#home\" class=\"scroll\" id=\"toTop\" style=\"display: block;\">\n");
      out.write("\t\t\t<span id=\"toTopHover\" style=\"opacity: 1;\"> </span>\n");
      out.write("\t\t</a>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
