
package org.gnuhpc.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayHello", targetNamespace = "http://wsServer.gnuhpc.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGreeting", targetNamespace = "http://wsServer.gnuhpc.org/", className = "org.gnuhpc.wsClient.GetGreeting")
    @ResponseWrapper(localName = "getGreetingResponse", targetNamespace = "http://wsServer.gnuhpc.org/", className = "org.gnuhpc.wsClient.GetGreetingResponse")
    @Action(input = "http://wsServer.gnuhpc.org/SayHello/getGreetingRequest", output = "http://wsServer.gnuhpc.org/SayHello/getGreetingResponse")
    public String getGreeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
