
package com.group3.util.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "smsSoap", targetNamespace = "http://106.ihuyi.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsSoap {


    /**
     * �ύ����:<br>����˵��:<br>account:�˺�<br>password:����<br>mobile:�ֻ����<br>content:��������
     * 
     * @param content
     * @param account
     * @param password
     * @param mobile
     * @return
     *     returns pers.william.sms.SubmitResult
     */
    @WebMethod(operationName = "Submit", action = "http://106.ihuyi.cn/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "Submit", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.Submit")
    @ResponseWrapper(localName = "SubmitResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.SubmitResponse")
    public SubmitResult submit(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password,
        @WebParam(name = "mobile", targetNamespace = "http://106.ihuyi.cn/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://106.ihuyi.cn/")
        String content);

    /**
     * �޸Ķ����˺�����:<br>����˵��:<br>account:�˺�<br>password:������<br>newpassword:������
     * 
     * @param account
     * @param password
     * @param newpassword
     * @return
     *     returns pers.william.sms.ChangePasswordResult
     */
    @WebMethod(operationName = "ChangePassword", action = "http://106.ihuyi.cn/ChangePassword")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.ChangePasswordResponse")
    public ChangePasswordResult changePassword(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password,
        @WebParam(name = "newpassword", targetNamespace = "http://106.ihuyi.cn/")
        String newpassword);

    /**
     * ��ѯ�˻����:<br>����˵��:<br>account:��ѯ�û���<br>password:��ѯ�û�����
     * 
     * @param account
     * @param password
     * @return
     *     returns pers.william.sms.GetNumResult
     */
    @WebMethod(operationName = "GetNum", action = "http://106.ihuyi.cn/GetNum")
    @WebResult(name = "GetNumResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetNum", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetNum")
    @ResponseWrapper(localName = "GetNumResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetNumResponse")
    public GetNumResult getNum(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password);

    /**
     * ��ѯ�û��ظ�:<br>����˵��:<br>account:��ѯ�û���<br>password:��ѯ�û�����
     * 
     * @param account
     * @param password
     * @return
     *     returns pers.william.sms.GetReplyResult
     */
    @WebMethod(operationName = "GetReply", action = "http://106.ihuyi.cn/GetReply")
    @WebResult(name = "GetReplyResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetReply", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetReply")
    @ResponseWrapper(localName = "GetReplyResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetReplyResponse")
    public GetReplyResult getReply(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password);

    /**
     * ��ѯ���ͻ�ִ:<br>����˵��:<br>account:��ѯ�û���<br>password:��ѯ�û�����<br>smsid:��ˮ��
     * 
     * @param smsid
     * @param account
     * @param password
     * @return
     *     returns pers.william.sms.GetReportResult
     */
    @WebMethod(operationName = "GetReport", action = "http://106.ihuyi.cn/GetReport")
    @WebResult(name = "GetReportResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetReport", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetReport")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetReportResponse")
    public GetReportResult getReport(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password,
        @WebParam(name = "smsid", targetNamespace = "http://106.ihuyi.cn/")
        String smsid);

    /**
     * ��ѯ���ͻ�ִ:<br>����˵��:<br>smsid:��ˮ��
     * 
     * @param smsid
     * @return
     *     returns pers.william.sms.QueryResult
     */
    @WebMethod(operationName = "Query", action = "http://106.ihuyi.cn/Query")
    @WebResult(name = "QueryResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "Query", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.QueryResponse")
    public QueryResult query(
        @WebParam(name = "smsid", targetNamespace = "http://106.ihuyi.cn/")
        String smsid);

    /**
     * ��ȡ�ͷ���Ϣ:<br>����˵��:<br>account:��ѯ�û���<br>password:��ѯ�û�����
     * 
     * @param account
     * @param password
     * @return
     *     returns pers.william.sms.GetKeFuResult
     */
    @WebMethod(operationName = "GetKeFu", action = "http://106.ihuyi.cn/GetKeFu")
    @WebResult(name = "GetKeFuResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetKeFu", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetKeFu")
    @ResponseWrapper(localName = "GetKeFuResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.GetKeFuResponse")
    public GetKeFuResult getKeFu(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password);

    /**
     * �汾��Ϣ,��������ʾ:<br>����˵��:
     * 
     * @return
     *     returns pers.william.sms.VersionInfoResult
     */
    @WebMethod(operationName = "VersionInfo", action = "http://106.ihuyi.cn/VersionInfo")
    @WebResult(name = "VersionInfoResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "VersionInfo", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.VersionInfo")
    @ResponseWrapper(localName = "VersionInfoResponse", targetNamespace = "http://106.ihuyi.cn/", className = "pers.william.sms.VersionInfoResponse")
    public VersionInfoResult versionInfo();

}
