/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-11-09 08:24:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content.queryInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Login</title>\n");
      out.write("<script src=\"js/jquery-1.7.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"application/x-javascript\">\n");
      out.write("\n");
      out.write("function login() {\n");
      out.write("\t//alert(qqq);\n");
      out.write("\tvar name = document.getElementById(\"name\").value;\n");
      out.write("\t//alert(qqq);\n");
      out.write("\tvar password = document.getElementById(\"password\").value;\n");
      out.write("\tconsole.log(name+\":\"+password);\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype : \"POST\",\n");
      out.write("\t\turl : \"userLogin\",\n");
      out.write("\t\tdata : \"name=\"\n");
      out.write("\t\t\t\t+ name\n");
      out.write("\t\t\t\t+ \"&password=\"\n");
      out.write("\t\t\t\t+ password,\n");
      out.write("\t\tsuccess : function(user) {\n");
      out.write("\t\t\tconsole.log(user);\n");
      out.write("\t\t\tif (user.id == null) {\n");
      out.write("\t\t\t\tconsole.log(user);\n");
      out.write("\t\t\t\talert( \"用户名或密码不正确,请检查后重新输入\");\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$(\".close\").click();\n");
      out.write("\t\t\t\t$(\".modal-backdrop\").hide();\n");
      out.write("\t\t\t\tloginId = user.id;\n");
      out.write("\t\t\t\tuserName = user.userName;\n");
      out.write("\t\t\t\ttestIfLogin();\n");
      out.write("\t\t\t\t//window.location.reload();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t//$(\".modal-dialog\").attr(\"hidden\",\"hidden\");\n");
      out.write("\t\t},\n");
      out.write("\t\t\n");
      out.write("\t}) \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Id\" >\n");
      out.write("<input type=\"text\" name=\"password\" id=\"password\" placeholder=\"password\">\n");
      out.write("<input type=\"button\" value=\"登录\" onclick=\"login()\">\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
